### PR TITLE
use promise pool to handle batch

### PR DESCRIPTION
**Pull request by fa93hws**
Use promise pool to replace the existing batching.

Batching will wait for x promises with `Promise.all`, this improves efficiency a lot but it also have to wait till the last promise in the batch to resolve, which is not very optimised.
As a comparasion, promise pool will push a new one into the queue whenever there is a promise resolved.
When running locally, this improves the time consumption of a `find_affected_files` to 50 seconds from 65 seconds.

`@supercharge/promise-pool` is a simply library that depends on nothing https://github.com/supercharge/promise-pool/blob/main/package.json.

### CODE REVIEW

**Review by joscha — COMMENTED** [review]
Is this the same performance as a batch size of 1?

**Comment by fa93hws** [comment]
> Is this the same performance as a batch size of 1?

No, for detail:
Batch size = 1 => 1.48 minutes
Batch size = 10, with Promise.all => 1.05 minutes
Batch size = 10, with promise pool => 50 seconds

**Review by joscha — APPROVED** [review]

**Comment by joscha** [comment]
You can follow the instructions to get a new release!

**Comment by fa93hws** [comment]
> You can follow the instructions to get a new release!

Thanks!

**Comment by fa93hws** [comment]
Does that sounds like we need to update the npm token? https://github.com/canva-public/dependency-tree/runs/7892140078?check_suite_focus=true#step:6:47

**Pull request merged**
